<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.16.0" />
    <PackageReference Include="Discord.Net.Rest" Version="3.16.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-rc0003" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoogleApis\GoogleApis.csproj" />
    <ProjectReference Include="..\Pwe.AzureBloBStore\Pwe.AzureBlobStore.csproj" />
    <ProjectReference Include="..\pwe.OverpassTiles\Pwe.OverpassTiles.csproj" />
    <ProjectReference Include="..\Pwe.Shared\Pwe.Shared.csproj" />
    <ProjectReference Include="..\Pwe.World\Pwe.World.csproj" />
  </ItemGroup>

</Project>
